accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', views.Home.as_view(), name='home'),

]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
]

pollsApp1/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
		question_text = models.CharField(max_length=200)
		pub_date = models.DateTimeField('date published')
		def __str__(self):
				return self.question_text
		def was_published_recently(self):
			now = timezone.now()
			return now - datetime.timedelta(days=1) <= self.pub_date <= now
		was_published_recently.admin_order_field = 'pub_date'
		was_published_recently.boolean = True
		was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
				return self.choice_text

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import TemplateView 


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class LogIn(generic.CreateView):
    success_url = '/polls'
    template_name = 'login.html'


class Home(TemplateView):
    template_name = 'home.html'

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

from django.contrib.auth.mixins import LoginRequiredMixin




class IndexView(LoginRequiredMixin, generic.ListView):
	login_url = '/login/'
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

accounts/templates/home.html
<!-- templates/home.html -->
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class = "container-fluid text-center">
    <h1>polls app</h1>
	{% if user.is_authenticated %}
		<p>Hi {{ user.username }}</p>
		<a href="{% url 'polls:index' %}">Go to polls</a>
		<a href="{% url 'logout' %}">Log out</a>
	{% else %}
		<p><a href="{% url 'signup' %}">Sign Up</a></p>
		<p><a href="{% url 'login' %}">Log In </a></p>
	{% endif %}
</div>

accounts/templates/signup.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


<div class="container-fluid">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">

		<h2> signup </h2>
		{# Display a form #}
		<form method="post" class="form">
		  {% csrf_token %}
		  {% bootstrap_form form %}
		  {% buttons %}
		    <button type="submit" class="btn btn-primary btn-block">Submit</button>
		  {% endbuttons %}
		</form>
	</div>
	<div class="col-sm-2"></div>
</div>

polls/templates/polls/detail.html
{% load static %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


  <nav class="navbar navbar-default bg-1">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'polls:index' %}">Hi {{ user.username }}!</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="container-fluid">
	<div class="col-sm-4"></div>
	<div class="col-sm-4">

		<h1>{{ question.question_text }}</h1>

		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}



		<form action="{% url 'polls:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
		    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
		    <label class="btn " for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		{% endfor %}
		<input type="submit" class="btn btn-primary btn-block" value="Vote" />
		<a href="{% url 'polls:index' %}">Go back to Polls</a>
		</form>
	</div>
	<div class="col-sm-4"></div>
</div>

polls/templates/polls/index.html
{% load static %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

  <nav class="navbar navbar-default bg-1">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Hi {{ user.username }}!</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="container-fluid text-center">
  <div class="col-sm-4"></div>
  <div class="col-sm-4 pollscontainer" ">
      <h2 class = "text">Polls</h2>
      {% if latest_question_list %}
        <div class="list-group">
         {% for question in latest_question_list %}
               <a class="list-group-item" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
          {% endfor %}
        </div>
      {% else %}
            <p>No polls are available.</p>
      {% endif %}
  </div>
  <div class="col-sm-4"></div>
</div>

polls/templates/polls/results.html
{% load static %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

  <nav class="navbar navbar-default bg-1">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'polls:index' %}">Hi {{ user.username }}!</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>
	
<div class="container-fluid text-center">
	<div class="col-sm-4"></div>
	<div class="col-sm-4">
		<h1>{{ question.question_text }}</h1>

		<ul class = "list-group">
		{% for choice in question.choice_set.all %}
		    <li class= "list-group-item">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
		{% endfor %}
		</ul>

	<a href="{% url 'polls:index' %}">Go back to Polls</a>
	</div>
	<div class="col-sm-4"></div>
</div>